/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as StringRouteImport } from './routes/string'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DpRouteImport } from './routes/dp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const StringRoute = StringRouteImport.update({
  id: '/string',
  path: '/string',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DpRoute = DpRouteImport.update({
  id: '/dp',
  path: '/dp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProblemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/string': typeof StringRoute
  '/tree': typeof TreeRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/string': typeof StringRoute
  '/tree': typeof TreeRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/string': typeof StringRoute
  '/tree': typeof TreeRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dp'
    | '/graph'
    | '/history'
    | '/learn'
    | '/problems'
    | '/searching'
    | '/sorting'
    | '/string'
    | '/tree'
    | '/problems/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dp'
    | '/graph'
    | '/history'
    | '/learn'
    | '/problems'
    | '/searching'
    | '/sorting'
    | '/string'
    | '/tree'
    | '/problems/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dp'
    | '/graph'
    | '/history'
    | '/learn'
    | '/problems'
    | '/searching'
    | '/sorting'
    | '/string'
    | '/tree'
    | '/problems/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DpRoute: typeof DpRoute
  GraphRoute: typeof GraphRoute
  HistoryRoute: typeof HistoryRoute
  LearnRoute: typeof LearnRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  SearchingRoute: typeof SearchingRoute
  SortingRoute: typeof SortingRoute
  StringRoute: typeof StringRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/string': {
      id: '/string'
      path: '/string'
      fullPath: '/string'
      preLoaderRoute: typeof StringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp': {
      id: '/dp'
      path: '/dp'
      fullPath: '/dp'
      preLoaderRoute: typeof DpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof ProblemsRoute
    }
  }
}

interface ProblemsRouteChildren {
  ProblemsSlugRoute: typeof ProblemsSlugRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsSlugRoute: ProblemsSlugRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DpRoute: DpRoute,
  GraphRoute: GraphRoute,
  HistoryRoute: HistoryRoute,
  LearnRoute: LearnRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  SearchingRoute: SearchingRoute,
  SortingRoute: SortingRoute,
  StringRoute: StringRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
